Adding multi-platform support for linux/amd64 and linux/arm64 (#83)
* Adding multi-platform support for linux/amd64 and linux/arm64

* Bumped GHA versions
Added `--platform` option to `docker build` commands in e2e tests
Added `PLATFORM` variable to Makefile for local builds
Golang version update
Dependency updates

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* Need to use `docker buildx` to get platform flags in Dockerfile

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* `docker buildx` is apparently not supported in GHA

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* Trying to get `BUILDPLATFORM` down to Dockerfiles.

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* Defaulted `BUILDPLATFORM`

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* Updated tests referring to old v1beta policy
Problem only shows when updating the kubebuilder-tools
  to 1.25.0 (when the v1beta policy was deprecated)

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* Updating e2e-tests
Added podman support for e2d tests

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* Testing e2e-tests w/`docker buildx build`
Tied to use the `--load` option instead of `--push` but didn't work
May be a Rancher Desktop issue
> error: docker exporter does not currently support exporting manifest lists

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* Added logic to handle podman buildx behavior differences
  `podman buildx` auto-loads the image into the local docker repo
  `podman buildx` doesn't support `--push` arg
  `docker pull` is not necessary with podman
Refactored create_dev_cluster.sh

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* Updated e2e-test node versions
Added both platforms to docker build commands in e2e-tests

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* Can't specify multiple platforms w/regular docker build

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* Updated quick-start.md

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* Major refactoring of create_dev_cluster.sh
Mainly for testing different platform and build configurations

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* Typos and logic

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* Typos and logic

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

* Typos and logic

Signed-off-by: Craig Ingram <cingram@us.ibm.com>

Signed-off-by: Craig Ingram <cingram@us.ibm.com>